# Generated by Django 4.2.2 on 2023-07-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='type',
        ),
        migrations.AddField(
            model_name='training',
            name='quantity_type',
            field=models.CharField(choices=[('Sets', 'Sets'), ('Time', 'Time')], default='Sets', max_length=30),
        ),
    ]
